name: CI/CD Pipeline

on:
  push:
    branches:
      - feature_fix_CICD
  pull_request:
    branches:
      - feature_fix_CICD

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0' 
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Deploy
        run: |
          echo "正在部署中..."
        
